include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_redundant_argument_values: false
    join_return_with_assignment: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    use_setters_to_change_properties: false
