include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude: 
    - "lib/generated/**"
    - "lib/firebase_options.dart"

linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_redundant_argument_values: false
    join_return_with_assignment: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
